//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 11:01:46 AM EAT 
//


package ke.co.workpoint.icms.model.exm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}eml_header"/>
 *         &lt;element ref="{}eml_body"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "emlHeader",
    "emlBody"
})
@XmlRootElement(name = "eml")
public class Eml {

    @XmlElement(name = "eml_header", required = true)
    protected EmlHeader emlHeader;
    @XmlElement(name = "eml_body", required = true)
    protected EmlBody emlBody;

    /**
     * Gets the value of the emlHeader property.
     * 
     * @return
     *     possible object is
     *     {@link EmlHeader }
     *     
     */
    public EmlHeader getEmlHeader() {
        return emlHeader;
    }

    /**
     * Sets the value of the emlHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmlHeader }
     *     
     */
    public void setEmlHeader(EmlHeader value) {
        this.emlHeader = value;
    }

    /**
     * Gets the value of the emlBody property.
     * 
     * @return
     *     possible object is
     *     {@link EmlBody }
     *     
     */
    public EmlBody getEmlBody() {
        return emlBody;
    }

    /**
     * Sets the value of the emlBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmlBody }
     *     
     */
    public void setEmlBody(EmlBody value) {
        this.emlBody = value;
    }

}
