//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 11:01:46 AM EAT 
//


package ke.co.workpoint.icms.model.exm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}third_party_list_ref"/>
 *         &lt;element ref="{}third_party_issue_date"/>
 *         &lt;element ref="{}impl_agency"/>
 *         &lt;element ref="{}exemption_channel"/>
 *         &lt;element ref="{}effective_date"/>
 *         &lt;element ref="{}expiry_date"/>
 *         &lt;element ref="{}tin"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "eml_header")
public class EmlHeader {

    @XmlElement(name = "third_party_list_ref", required = true)
    protected String thirdPartyListRef;
    @XmlElement(name = "third_party_issue_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar thirdPartyIssueDate;
    @XmlElement(name = "impl_agency", required = true)
    protected String implAgency;
    @XmlElement(name = "exemption_channel", required = true)
    protected String exemptionChannel;
    @XmlElement(name = "effective_date", required = true)
    protected XMLGregorianCalendar effectiveDate;
    @XmlElement(name = "expiry_date", required = true)
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(required = true)
    protected String tin;

    /**
     * Gets the value of the thirdPartyListRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThirdPartyListRef() {
        return thirdPartyListRef;
    }

    /**
     * Sets the value of the thirdPartyListRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThirdPartyListRef(String value) {
        this.thirdPartyListRef = value;
    }

    /**
     * Gets the value of the thirdPartyIssueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getThirdPartyIssueDate() {
        return thirdPartyIssueDate;
    }

    /**
     * Sets the value of the thirdPartyIssueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setThirdPartyIssueDate(XMLGregorianCalendar value) {
        this.thirdPartyIssueDate = value;
    }

    /**
     * Gets the value of the implAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImplAgency() {
        return implAgency;
    }

    /**
     * Sets the value of the implAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImplAgency(String value) {
        this.implAgency = value;
    }

    /**
     * Gets the value of the exemptionChannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExemptionChannel() {
        return exemptionChannel;
    }

    /**
     * Sets the value of the exemptionChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExemptionChannel(String value) {
        this.exemptionChannel = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEffectiveDate(XMLGregorianCalendar value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the tin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTin() {
        return tin;
    }

    /**
     * Sets the value of the tin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTin(String value) {
        this.tin = value;
    }

}
