//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 11:01:46 AM EAT 
//


package ke.co.workpoint.icms.model.exm;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}item_num"/>
 *         &lt;element ref="{}hs_code"/>
 *         &lt;element ref="{}item_desc"/>
 *         &lt;element ref="{}measure_unit"/>
 *         &lt;element ref="{}unit_num"/>
 *         &lt;element ref="{}unit_currency"/>
 *         &lt;element ref="{}unit_value"/>
 *         &lt;element ref="{}is_im_duty_exm"/>
 *         &lt;element ref="{}duty_percent_exempted"/>
 *         &lt;element ref="{}is_vat_exm"/>
 *         &lt;element ref="{}is_excise_exm"/>
 *         &lt;element ref="{}is_idf_exempt"/>
 *         &lt;element ref="{}is_rdl_exempt"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "item")
public class Item {

    @XmlElement(name = "item_num", required = true)
    protected String itemNum;
    @XmlElement(name = "hs_code", required = true)
    protected String hsCode;
    @XmlElement(name = "item_desc", required = true)
    protected String itemDesc;
    @XmlElement(name = "measure_unit", required = true)
    protected String measureUnit;
    @XmlElement(name = "unit_num", required = true)
    protected BigDecimal unitNum;
    @XmlElement(name = "unit_currency", required = true)
    protected String unitCurrency;
    @XmlElement(name = "unit_value", required = true)
    protected BigDecimal unitValue;
    @XmlElement(name = "is_im_duty_exm", required = true)
    protected String isImDutyExm;
    @XmlElement(name = "duty_percent_exempted", required = true)
    protected BigDecimal dutyPercentExempted;
    @XmlElement(name = "is_vat_exm", required = true)
    protected String isVatExm;
    @XmlElement(name = "is_excise_exm", required = true)
    protected String isExciseExm;
    @XmlElement(name = "is_idf_exempt", required = true)
    protected String isIdfExempt;
    @XmlElement(name = "is_rdl_exempt", required = true)
    protected String isRdlExempt;
    
    public Item() {
	}

    public Item(String itemNum, String hsCode, String itemDesc, String measureUnit, BigDecimal unitNum,
			String unitCurrency, BigDecimal unitValue, String isImDutyExm, BigDecimal dutyPercentExempted,
			String isVatExm, String isExciseExm, String isIdfExempt, String isRdlExempt) {
		super();
		this.itemNum = itemNum;
		this.hsCode = hsCode;
		this.itemDesc = itemDesc;
		this.measureUnit = measureUnit;
		this.unitNum = unitNum;
		this.unitCurrency = unitCurrency;
		this.unitValue = unitValue;
		this.isImDutyExm = isImDutyExm;
		this.dutyPercentExempted = dutyPercentExempted;
		this.isVatExm = isVatExm;
		this.isExciseExm = isExciseExm;
		this.isIdfExempt = isIdfExempt;
		this.isRdlExempt = isRdlExempt;
	}

	/**
     * Gets the value of the itemNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemNum() {
        return itemNum;
    }

    /**
     * Sets the value of the itemNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemNum(String value) {
        this.itemNum = value;
    }

    /**
     * Gets the value of the hsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHsCode() {
        return hsCode;
    }

    /**
     * Sets the value of the hsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHsCode(String value) {
        this.hsCode = value;
    }

    /**
     * Gets the value of the itemDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * Sets the value of the itemDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItemDesc(String value) {
        this.itemDesc = value;
    }

    /**
     * Gets the value of the measureUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasureUnit() {
        return measureUnit;
    }

    /**
     * Sets the value of the measureUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasureUnit(String value) {
        this.measureUnit = value;
    }

    /**
     * Gets the value of the unitNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitNum() {
        return unitNum;
    }

    /**
     * Sets the value of the unitNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitNum(BigDecimal value) {
        this.unitNum = value;
    }

    /**
     * Gets the value of the unitCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitCurrency() {
        return unitCurrency;
    }

    /**
     * Sets the value of the unitCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitCurrency(String value) {
        this.unitCurrency = value;
    }

    /**
     * Gets the value of the unitValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUnitValue() {
        return unitValue;
    }

    /**
     * Sets the value of the unitValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUnitValue(BigDecimal value) {
        this.unitValue = value;
    }

    /**
     * Gets the value of the isImDutyExm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsImDutyExm() {
        return isImDutyExm;
    }

    /**
     * Sets the value of the isImDutyExm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsImDutyExm(String value) {
        this.isImDutyExm = value;
    }

    /**
     * Gets the value of the dutyPercentExempted property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDutyPercentExempted() {
        return dutyPercentExempted;
    }

    /**
     * Sets the value of the dutyPercentExempted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDutyPercentExempted(BigDecimal value) {
        this.dutyPercentExempted = value;
    }

    /**
     * Gets the value of the isVatExm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsVatExm() {
        return isVatExm;
    }

    /**
     * Sets the value of the isVatExm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsVatExm(String value) {
        this.isVatExm = value;
    }

    /**
     * Gets the value of the isExciseExm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsExciseExm() {
        return isExciseExm;
    }

    /**
     * Sets the value of the isExciseExm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsExciseExm(String value) {
        this.isExciseExm = value;
    }

    /**
     * Gets the value of the isIdfExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsIdfExempt() {
        return isIdfExempt;
    }

    /**
     * Sets the value of the isIdfExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsIdfExempt(String value) {
        this.isIdfExempt = value;
    }

    /**
     * Gets the value of the isRdlExempt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsRdlExempt() {
        return isRdlExempt;
    }

    /**
     * Sets the value of the isRdlExempt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsRdlExempt(String value) {
        this.isRdlExempt = value;
    }

}
