//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.20 at 11:01:46 AM EAT 
//


package ke.co.workpoint.icms.model.exm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}eml"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eml"
})
@XmlRootElement(name = "message_body")
public class MessageBody {

    @XmlElement(required = true)
    protected Eml eml;
    
    /**
     * Gets the value of the eml property.
     * 
     * @return
     *     possible object is
     *     {@link Eml }
     *     
     */
    public Eml getEml() {
        return eml;
    }

    /**
     * Sets the value of the eml property.
     * 
     * @param value
     *     allowed object is
     *     {@link Eml }
     *     
     */
    public void setEml(Eml value) {
        this.eml = value;
    }
}
